/** TwitchCraft #command store catalog — shorthand-first. */
window.TWITCHCRAFT_STORE = {
  meta: {
    title: "TwitchCraft Command Store",
    subtitle: "Copy a #command · paste in Twitch chat",
    prefix: "#",
  },

  items: [
    {
      type: "help",
      text: "Any vanilla item works with #give — this list is just a starter guide.",
    },
    {
      type: "help",
      text: "Player heads: #give player_head[SkullBott] (or SkullOwner:\"Name\").",
    },
    { name: "Player Head (SkullBott)", cmd: "#give player_head[SkullBott]" },
    // Priority starter pack
    { name: "Enchanting Bottle", cmd: "#give experience_bottle 16" },
    { name: "Enchanted Golden Apple", cmd: "#give enchanted_golden_apple 1" },
    { name: "Iron Ingot", cmd: "#give iron_ingot 8" },
    { name: "Gold Ingot", cmd: "#give gold_ingot 8" },
    { name: "Diamond", cmd: "#give diamond 1" },
    { name: "Villager Spawn Egg", cmd: "#give villager_spawn_egg 1" },
    { name: "Bow", cmd: "#give bow" },
    { name: "Fishing Rod", cmd: "#give fishing_rod" },
    { name: "Healing Potion", cmd: "#give potion[healing]" },
    { name: "Bread", cmd: "#give bread 16" },
    { name: "Rotten Flesh", cmd: "#give rotten_flesh 32" },
    { name: "Oak Log", cmd: "#give oak_log 32" },
    { name: "Cod Bucket", cmd: "#give cod_bucket" },
    { name: "Salmon Bucket", cmd: "#give salmon_bucket" },
    { name: "Firework Rocket", cmd: "#give firework_rocket 16" },
    { name: "TNT", cmd: "#give tnt 8" },

    // More new-player useful
    { name: "Torch", cmd: "#give torch 64" },
    { name: "Coal", cmd: "#give coal 64" },
    { name: "Stick", cmd: "#give stick 64" },
    { name: "Cobblestone", cmd: "#give cobblestone 64" },
    { name: "Dirt", cmd: "#give dirt 64" },
    { name: "Sand", cmd: "#give sand 64" },
    { name: "Glass", cmd: "#give glass 32" },
    { name: "Crafting Table", cmd: "#give crafting_table" },
    { name: "Furnace", cmd: "#give furnace" },
    { name: "Chest", cmd: "#give chest 4" },
    { name: "Bed", cmd: "#give white_bed" },
    { name: "Oak Sapling", cmd: "#give oak_sapling 16" },
    { name: "Wheat Seeds", cmd: "#give wheat_seeds 32" },
    { name: "Carrot", cmd: "#give carrot 16" },
    { name: "Potato", cmd: "#give potato 16" },
    { name: "Bone Meal", cmd: "#give bone_meal 32" },
    { name: "Cooked Beef", cmd: "#give cooked_beef 16" },
    { name: "Cooked Porkchop", cmd: "#give cooked_porkchop 16" },
    { name: "Apple", cmd: "#give apple 16" },
    { name: "Golden Apple", cmd: "#give golden_apple 4" },
    { name: "Water Bucket", cmd: "#give water_bucket" },
    { name: "Lava Bucket", cmd: "#give lava_bucket" },
    { name: "Bucket", cmd: "#give bucket" },
    { name: "Milk Bucket", cmd: "#give milk_bucket" },
    { name: "Arrow", cmd: "#give arrow 64" },
    { name: "String", cmd: "#give string 32" },
    { name: "Leather", cmd: "#give leather 16" },
    { name: "Feather", cmd: "#give feather 16" },
    { name: "Flint", cmd: "#give flint 16" },
    { name: "Flint and Steel", cmd: "#give flint_and_steel" },
    { name: "Shears", cmd: "#give shears" },
    { name: "Compass", cmd: "#give compass" },
    { name: "Clock", cmd: "#give clock" },
    { name: "Map", cmd: "#give map" },
    { name: "Boat", cmd: "#give oak_boat" },
    { name: "Minecart", cmd: "#give minecart" },
    { name: "Rail", cmd: "#give rail 32" },
    { name: "Ladder", cmd: "#give ladder 32" },
    { name: "Oak Planks", cmd: "#give oak_planks 64" },
    { name: "Spruce Log", cmd: "#give spruce_log 32" },
    { name: "Birch Log", cmd: "#give birch_log 32" },
    { name: "Copper Ingot", cmd: "#give copper_ingot 8" },
    { name: "Lapis Lazuli", cmd: "#give lapis_lazuli 32" },
    { name: "Redstone", cmd: "#give redstone 32" },
    { name: "Emerald", cmd: "#give emerald 8" },
    { name: "Obsidian", cmd: "#give obsidian 8" },
    { name: "Ender Pearl", cmd: "#give ender_pearl 8" },
    { name: "Shield", cmd: "#give shield" },
    { name: "Spyglass", cmd: "#give spyglass" },
    { name: "Name Tag", cmd: "#give name_tag" },
    { name: "Saddle", cmd: "#give saddle" },
    { name: "Lead", cmd: "#give lead 4" },
    { name: "Lantern", cmd: "#give lantern 8" },
    { name: "Campfire", cmd: "#give campfire" },
    { name: "Hay Bale", cmd: "#give hay_block 8" },
    { name: "Scaffolding", cmd: "#give scaffolding 32" },
  ],

  equipment: [
    {
      type: "help",
      text: "Enchanted gear: put enchants in [brackets] after the item. Level is a number after the name.",
    },
    {
      type: "help",
      text: "1 enchant — #give diamond_sword[sharpness 5]",
    },
    {
      type: "help",
      text: "3 enchants — #give netherite_pickaxe[efficiency 5, fortune 3, unbreaking 3]",
    },

    { type: "section", title: "T1 — Iron" },
    { name: "Iron Sword", cmd: "#give iron_sword" },
    { name: "Iron Pickaxe", cmd: "#give iron_pickaxe" },
    { name: "Iron Axe", cmd: "#give iron_axe" },
    { name: "Iron Shovel", cmd: "#give iron_shovel" },
    { name: "Iron Hoe", cmd: "#give iron_hoe" },
    { name: "Iron Helmet", cmd: "#give iron_helmet" },
    { name: "Iron Chestplate", cmd: "#give iron_chestplate" },
    { name: "Iron Leggings", cmd: "#give iron_leggings" },
    { name: "Iron Boots", cmd: "#give iron_boots" },
    { name: "Bow", cmd: "#give bow" },
    { name: "Shield", cmd: "#give shield" },

    { type: "section", title: "T2 — Diamond" },
    { name: "Diamond Sword", cmd: "#give diamond_sword" },
    { name: "Diamond Pickaxe", cmd: "#give diamond_pickaxe" },
    { name: "Diamond Axe", cmd: "#give diamond_axe" },
    { name: "Diamond Shovel", cmd: "#give diamond_shovel" },
    { name: "Diamond Hoe", cmd: "#give diamond_hoe" },
    { name: "Diamond Helmet", cmd: "#give diamond_helmet" },
    { name: "Diamond Chestplate", cmd: "#give diamond_chestplate" },
    { name: "Diamond Leggings", cmd: "#give diamond_leggings" },
    { name: "Diamond Boots", cmd: "#give diamond_boots" },
    { name: "Bow", cmd: "#give bow" },
    { name: "Crossbow", cmd: "#give crossbow" },
    { name: "Shield", cmd: "#give shield" },

    { type: "section", title: "T3 — Netherite" },
    { name: "Netherite Sword", cmd: "#give netherite_sword" },
    { name: "Netherite Pickaxe", cmd: "#give netherite_pickaxe" },
    { name: "Netherite Axe", cmd: "#give netherite_axe" },
    { name: "Netherite Shovel", cmd: "#give netherite_shovel" },
    { name: "Netherite Hoe", cmd: "#give netherite_hoe" },
    { name: "Netherite Helmet", cmd: "#give netherite_helmet" },
    { name: "Netherite Chestplate", cmd: "#give netherite_chestplate" },
    { name: "Netherite Leggings", cmd: "#give netherite_leggings" },
    { name: "Netherite Boots", cmd: "#give netherite_boots" },
    { name: "Trident", cmd: "#give trident" },
    { name: "Elytra", cmd: "#give elytra" },
    { name: "Shield", cmd: "#give shield" },
  ],

  arrows: [
    { type: "section", title: "Gear" },
    { name: "Bow", cmd: "#give bow" },
    { name: "Crossbow", cmd: "#give crossbow" },
    { name: "Shield", cmd: "#give shield" },

    { type: "section", title: "Arrows" },
    { name: "Arrow ×64", cmd: "#give arrow 64" },
    { name: "Spectral Arrow ×16", cmd: "#give spectral_arrow 16" },
    { name: "Fire Resistance", cmd: "#give arrow[fire resistance] 16" },
    { name: "Harming", cmd: "#give arrow[harming] 16" },
    { name: "Harming II", cmd: "#give arrow[harming 2] 16" },
    { name: "Healing", cmd: "#give arrow[healing] 16" },
    { name: "Healing II", cmd: "#give arrow[healing 2] 16" },
    { name: "Invisibility", cmd: "#give arrow[invisibility] 16" },
    { name: "Leaping", cmd: "#give arrow[leaping] 16" },
    { name: "Leaping II", cmd: "#give arrow[leaping 2] 16" },
    { name: "Long Poison", cmd: "#give arrow[long poison] 16" },
    { name: "Long Weakness", cmd: "#give arrow[weakness 2] 16" },
    { name: "Night Vision", cmd: "#give arrow[night vision] 16" },
    { name: "Poison", cmd: "#give arrow[poison] 16" },
    { name: "Poison II", cmd: "#give arrow[poison 2] 16" },
    { name: "Regen II", cmd: "#give arrow[regen 2] 16" },
    { name: "Regeneration", cmd: "#give arrow[regen] 16" },
    { name: "Slow Falling", cmd: "#give arrow[slow falling] 16" },
    { name: "Slowness", cmd: "#give arrow[slowness] 16" },
    { name: "Slowness II", cmd: "#give arrow[slowness 2] 16" },
    { name: "Swiftness", cmd: "#give arrow[swiftness] 16" },
    { name: "Swiftness II", cmd: "#give arrow[swiftness 2] 16" },
    { name: "Turtle Master", cmd: "#give arrow[turtle master] 16" },
    { name: "Turtle Master II", cmd: "#give arrow[turtle master 2] 16" },
    { name: "Water Breathing", cmd: "#give arrow[water breathing] 16" },
    { name: "Weakness", cmd: "#give arrow[weakness] 16" },
  ],

  books: [
    { name: "Aqua Affinity I", cmd: "#give enchanted_book[aqua affinity 1]" },
    { name: "Bane of Arthropods I", cmd: "#give enchanted_book[bane of arthropods 1]" },
    { name: "Binding Curse I", cmd: "#give enchanted_book[binding curse 1]" },
    { name: "Blast Protection I", cmd: "#give enchanted_book[blast protection 1]" },
    { name: "Channeling I", cmd: "#give enchanted_book[channeling 1]" },
    { name: "Depth Strider I", cmd: "#give enchanted_book[depth strider 1]" },
    { name: "Efficiency I", cmd: "#give enchanted_book[efficiency 1]" },
    { name: "Feather Falling I", cmd: "#give enchanted_book[feather falling 1]" },
    { name: "Fire Aspect I", cmd: "#give enchanted_book[fire aspect 1]" },
    { name: "Fire Protection I", cmd: "#give enchanted_book[fire protection 1]" },
    { name: "Flame I", cmd: "#give enchanted_book[flame 1]" },
    { name: "Fortune I", cmd: "#give enchanted_book[fortune 1]" },
    { name: "Frost Walker I", cmd: "#give enchanted_book[frost walker 1]" },
    { name: "Impaling I", cmd: "#give enchanted_book[impaling 1]" },
    { name: "Infinity I", cmd: "#give enchanted_book[infinity 1]" },
    { name: "Knockback I", cmd: "#give enchanted_book[knockback 1]" },
    { name: "Looting I", cmd: "#give enchanted_book[looting 1]" },
    { name: "Loyalty I", cmd: "#give enchanted_book[loyalty 1]" },
    { name: "Luck of the Sea I", cmd: "#give enchanted_book[luck of the sea 1]" },
    { name: "Lure I", cmd: "#give enchanted_book[lure 1]" },
    { name: "Mending I", cmd: "#give enchanted_book[mending 1]" },
    { name: "Multishot I", cmd: "#give enchanted_book[multishot 1]" },
    { name: "Piercing I", cmd: "#give enchanted_book[piercing 1]" },
    { name: "Power I", cmd: "#give enchanted_book[power 1]" },
    { name: "Projectile Protection I", cmd: "#give enchanted_book[projectile protection 1]" },
    { name: "Protection I", cmd: "#give enchanted_book[protection 1]" },
    { name: "Punch I", cmd: "#give enchanted_book[punch 1]" },
    { name: "Quick Charge I", cmd: "#give enchanted_book[quick charge 1]" },
    { name: "Respiration I", cmd: "#give enchanted_book[respiration 1]" },
    { name: "Riptide I", cmd: "#give enchanted_book[riptide 1]" },
    { name: "Sharpness I", cmd: "#give enchanted_book[sharpness 1]" },
    { name: "Silk Touch I", cmd: "#give enchanted_book[silk touch 1]" },
    { name: "Smite I", cmd: "#give enchanted_book[smite 1]" },
    { name: "Soul Speed I", cmd: "#give enchanted_book[soul speed 1]" },
    { name: "Soulbound I", cmd: "#give enchanted_book[soulbound 1]" },
    { name: "Sweeping Edge I", cmd: "#give enchanted_book[sweeping 1]" },
    { name: "Swift Sneak I", cmd: "#give enchanted_book[swift sneak 1]" },
    { name: "Thorns I", cmd: "#give enchanted_book[thorns 1]" },
    { name: "Unbreaking I", cmd: "#give enchanted_book[unbreaking 1]" },
    { name: "Vanishing Curse I", cmd: "#give enchanted_book[vanishing curse 1]" },
  ],

  potions: [
    { name: "Awkward", cmd: "#give potion[awkward]" },
    { name: "Fire Resistance", cmd: "#give potion[fire resistance]" },
    { name: "Healing II", cmd: "#give potion[healing 2]" },
    { name: "Invisibility", cmd: "#give potion[invisibility]" },
    { name: "Leaping II", cmd: "#give potion[leaping 2]" },
    { name: "Lingering Poison", cmd: "#give lingering_potion[long poison]" },
    { name: "Lingering Regen", cmd: "#give lingering_potion[regen]" },
    { name: "Lingering Slowness", cmd: "#give lingering_potion[slowness]" },
    { name: "Long Fire Resistance", cmd: "#give potion[long fire resistance]" },
    { name: "Long Night Vision", cmd: "#give potion[long night vision]" },
    { name: "Mundane", cmd: "#give potion[mundane]" },
    { name: "Night Vision", cmd: "#give potion[night vision]" },
    { name: "Regen II", cmd: "#give potion[regen 2]" },
    { name: "Slow Falling", cmd: "#give potion[slow falling]" },
    { name: "Splash Harming II", cmd: "#give splash_potion[strong harming]" },
    { name: "Splash Healing II", cmd: "#give splash_potion[healing 2]" },
    { name: "Splash Poison II", cmd: "#give splash_potion[poison 2]" },
    { name: "Splash Slowness II", cmd: "#give splash_potion[slowness 2]" },
    { name: "Splash Strength II", cmd: "#give splash_potion[strength 2]" },
    { name: "Splash Weakness II", cmd: "#give splash_potion[weakness 2]" },
    { name: "Strength II", cmd: "#give potion[strength 2]" },
    { name: "Swiftness", cmd: "#give potion[swiftness]" },
    { name: "Swiftness II", cmd: "#give potion[swiftness 2]" },
    { name: "Thick", cmd: "#give potion[thick]" },
    { name: "Turtle Master II", cmd: "#give potion[turtle master 2]" },
    { name: "Water Bottle", cmd: "#give potion[water]" },
    { name: "Water Breathing", cmd: "#give potion[water breathing]" },
  ],

  useful: [
    { name: "Armour Up", cmd: "#armourup", desc: "Resistance III." },
    { name: "Barrier", cmd: "#barrier", desc: "10 absorption hearts." },
    { name: "Bodyguard", cmd: "#bodyguard", desc: "Spawn 2 ally wolves." },
    { name: "Cleanse", cmd: "#cleanse", desc: "Clear harmful effects." },
    { name: "Dolphin", cmd: "#dolphin", desc: "Dolphin's Grace swim boost." },
    { name: "Feed", cmd: "#feed", desc: "Fill hunger + saturation." },
    { name: "Fire Resist", cmd: "#fireresist", desc: "Fire Resistance." },
    { name: "Glide", cmd: "#glide", desc: "Short levitation, then Slow Falling." },
    { name: "Glow Map", cmd: "#glowmap", desc: "Glow nearby hostiles." },
    { name: "Haste Up", cmd: "#hasteup", desc: "Haste III." },
    { name: "Heal Up", cmd: "#healup", desc: "Restore 5 hearts." },
    { name: "Leap", cmd: "#leap", desc: "Jump Boost III." },
    { name: "Light Up", cmd: "#lightup", desc: "Place a temporary light." },
    { name: "Loot Ping", cmd: "#lootping", desc: "Glow nearby chests & barrels." },
    { name: "Mend", cmd: "#mend", desc: "Free mending on gear." },
    { name: "Night Vision", cmd: "#nightvision", desc: "Night Vision." },
    { name: "Recall", cmd: "#recall", desc: "Set point, then teleport back." },
    { name: "Regen", cmd: "#regen", desc: "Regeneration II." },
    { name: "Saturation", cmd: "#saturation", desc: "Quick food restore." },
    { name: "Scout", cmd: "#scout", desc: "Night Vision + Speed." },
    { name: "Second Wind", cmd: "#secondwind", desc: "Burst Resistance + Regen." },
    { name: "Share Heal", cmd: "#shareheal", desc: "Heal you + nearest player." },
    { name: "Shield Wall", cmd: "#shieldwall", desc: "Resistance aura for nearby players." },
    { name: "Slow Falling", cmd: "#slowfalling", desc: "Slow Falling." },
    { name: "Sonic", cmd: "#sonic", desc: "Speed III." },
    { name: "Stash", cmd: "#stash", desc: "Open ender chest." },
    { name: "Totem", cmd: "#totem", desc: "One free Totem save." },
    { name: "Water Breath", cmd: "#waterbreath", desc: "Water Breathing." },
    { name: "XP Boost", cmd: "#xpboost", desc: "Luck II (bonus loot feel)." },
  ],

  /** Matches TwitchCraft CommandCatalog: Hostile / Neutral / Ally (config tags). */
  mobs: [
    {
      type: "help",
      text: "Safe-ground spawn when possible. Water mobs prefer water. Ally pets/golems bind when possible. #dolphinmob = dolphin entity (#dolphin is Dolphin's Grace).",
    },

    { type: "section", title: "Hostile" },
    { name: "Creeper", cmd: "#creeper" },
    { name: "Spider", cmd: "#spider" },
    { name: "Cave Spider", cmd: "#cavespider" },
    { name: "Zombie", cmd: "#zombie" },
    { name: "Zombie Villager", cmd: "#zombievillager" },
    { name: "Skeleton", cmd: "#skeleton" },
    { name: "Slime", cmd: "#slime" },
    { name: "Magma Cube", cmd: "#magmaslime" },
    { name: "Drowned", cmd: "#drowned" },
    { name: "Husk", cmd: "#husk" },
    { name: "Stray", cmd: "#stray" },
    { name: "Enderman", cmd: "#enderman" },
    { name: "Witch", cmd: "#witch" },
    { name: "Phantom", cmd: "#phantom" },
    { name: "Blaze", cmd: "#blaze" },
    { name: "Ghast", cmd: "#ghast" },
    { name: "Guardian", cmd: "#guardian" },
    { name: "Elder Guardian", cmd: "#elderguardian" },
    { name: "Silverfish", cmd: "#silverfish" },
    { name: "Endermite", cmd: "#endermite" },
    { name: "Pillager", cmd: "#pillager" },
    { name: "Vindicator", cmd: "#vindicator" },
    { name: "Evoker", cmd: "#evoker" },
    { name: "Vex", cmd: "#vex" },
    { name: "Ravager", cmd: "#ravager" },
    { name: "Shulker", cmd: "#shulker" },
    { name: "Wither Skeleton", cmd: "#witherskeleton" },
    { name: "Hoglin", cmd: "#hoglin" },
    { name: "Zoglin", cmd: "#zoglin" },
    { name: "Piglin Brute", cmd: "#piglinbrute" },
    { name: "Warden", cmd: "#warden" },

    { type: "section", title: "Neutral" },
    { name: "Cow", cmd: "#cow" },
    { name: "Mooshroom", cmd: "#mooshroom" },
    { name: "Pig", cmd: "#pig" },
    { name: "Chicken", cmd: "#chicken" },
    { name: "Sheep", cmd: "#sheep" },
    { name: "Rabbit", cmd: "#rabbit" },
    { name: "Squid", cmd: "#squid" },
    { name: "Glow Squid", cmd: "#glowsquid" },
    { name: "Cod", cmd: "#cod" },
    { name: "Salmon", cmd: "#salmon" },
    { name: "Tropical Fish", cmd: "#tropicalfish" },
    { name: "Pufferfish", cmd: "#pufferfish" },
    { name: "Tadpole", cmd: "#tadpole" },
    { name: "Dolphin", cmd: "#dolphinmob" },
    { name: "Axolotl", cmd: "#axolotl" },
    { name: "Bee", cmd: "#bee" },
    { name: "Goat", cmd: "#goat" },
    { name: "Fox", cmd: "#fox" },
    { name: "Frog", cmd: "#frog" },
    { name: "Panda", cmd: "#panda" },
    { name: "Polar Bear", cmd: "#polarbear" },
    { name: "Ocelot", cmd: "#ocelot" },
    { name: "Bat", cmd: "#bat" },
    { name: "Turtle", cmd: "#turtle" },
    { name: "Camel", cmd: "#camel" },
    { name: "Sniffer", cmd: "#sniffer" },
    { name: "Strider", cmd: "#strider" },
    { name: "Piglin", cmd: "#piglin" },
    { name: "Zombified Piglin", cmd: "#zombifiedpiglin" },
    { name: "Villager", cmd: "#villager" },
    { name: "Wandering Trader", cmd: "#wanderingtrader" },
    { name: "Skeleton Horse", cmd: "#skeletonhorse" },
    { name: "Zombie Horse", cmd: "#zombiehorse" },

    { type: "section", title: "Ally" },
    { name: "Cat", cmd: "#cat" },
    { name: "Wolf / Dog", cmd: "#dog" },
    { name: "Horse", cmd: "#horse" },
    { name: "Donkey", cmd: "#donkey" },
    { name: "Mule", cmd: "#mule" },
    { name: "Parrot", cmd: "#parrot" },
    { name: "Llama", cmd: "#llama" },
    { name: "Trader Llama", cmd: "#traderllama" },
    { name: "Allay", cmd: "#allay" },
    { name: "Iron Golem", cmd: "#irongolem" },
    { name: "Snow Golem", cmd: "#snowgolem" },
  ],

  curses: [
    { name: "Angry Bee", cmd: "#angrybee", desc: "Bee that pelts you with eggs." },
    { name: "Bad Bat", cmd: "#badbat", desc: "Steals a hotbar item and flees." },
    { name: "Bad Knight", cmd: "#badknight", desc: "Mounted skeleton hunter." },
    { name: "Bad Potato", cmd: "#badpotato", desc: "Crafts become poisonous potatoes." },
    { name: "Blink", cmd: "#blink", desc: "Random short teleport." },
    { name: "Bokuto", cmd: "#bokuto", desc: "Swords become sticks." },
    { name: "Butterfingers", cmd: "#butterfingers", desc: "Hits/breaks drop your held item." },
    { name: "Cloning", cmd: "#cloning", desc: "Hitting a mob spawns clones." },
    { name: "Cockbomb", cmd: "#cockbomb", desc: "Explosive chicken with iron drops." },
    { name: "Crop Rot", cmd: "#croprot", desc: "Reset nearby crops." },
    { name: "Disarm", cmd: "#disarm", desc: "Drop main hand." },
    { name: "Drunk", cmd: "#drunk", desc: "Invert movement & look." },
    { name: "Ender Swap", cmd: "#enderswap", desc: "Swap places when you hit a mob." },
    { name: "Feral", cmd: "#feral", desc: "Friendly mobs turn hostile." },
    { name: "Fool's Gold", cmd: "#foolsgold", desc: "Ores drop dirt." },
    { name: "Gravel", cmd: "#gravel", desc: "Gravel keeps falling ahead." },
    { name: "Hiccups", cmd: "#hiccups", desc: "Forced jumping." },
    { name: "Howler", cmd: "#howler", desc: "Mail that hunts you when opened." },
    { name: "Hungry", cmd: "#hungry", desc: "Hunger effect." },
    { name: "Infested", cmd: "#infested", desc: "Mining may spawn silverfish." },
    { name: "Jail", cmd: "#jail", desc: "Temporary glass cage." },
    { name: "Magnet Off", cmd: "#magnetoff", desc: "Can't pick up items." },
    { name: "Midas", cmd: "#midas", desc: "Kills & ores become raw gold." },
    { name: "Nightmare", cmd: "#nightmare", desc: "Night + angry phantoms." },
    { name: "Raid", cmd: "#raid", desc: "Start a raid / pillagers." },
    { name: "Rust", cmd: "#rust", desc: "Halve a hotbar item's durability." },
    { name: "Shuffle", cmd: "#shuffle", desc: "Hotbar keeps reshuffling." },
    { name: "Static Shock", cmd: "#staticshock", desc: "Placing blocks can zap you." },
    { name: "Stinky", cmd: "#stinky", desc: "Empty slots fill with rotten flesh." },
    { name: "Vampirism", cmd: "#vampirism", desc: "Burn in sun; buffed at night." },
    { name: "Voidstep", cmd: "#voidstep", desc: "Banished to the End, then return." },
    { name: "Webbed", cmd: "#webbed", desc: "Cobweb trap on you." },
    { name: "Yeet", cmd: "#yeet", desc: "Random launch any way." },
    { name: "Yeet N", cmd: "#yeet N", desc: "Launch forward." },
    { name: "Yeet S", cmd: "#yeet S", desc: "Launch back." },
    { name: "Yeet E", cmd: "#yeet E", desc: "Launch right." },
    { name: "Yeet W", cmd: "#yeet W", desc: "Launch left." },
    { name: "Yeet U", cmd: "#yeet U", desc: "Launch straight up." },
  ],
};
