/** TwichCraft #command store catalog — shorthand-first. */
window.TWITCHCRAFT_STORE = {
  meta: {
    title: "TwichCraft Command Store",
    subtitle: "Copy a #command · paste in Twitch chat",
    prefix: "#",
  },

  items: [
    { name: "Dirt", cmd: "#give dirt 64" },
    { name: "Cobblestone", cmd: "#give cobblestone 64" },
    { name: "Stone", cmd: "#give stone 64" },
    { name: "Deepslate", cmd: "#give deepslate 64" },
    { name: "Oak Log", cmd: "#give oak_log 32" },
    { name: "Spruce Log", cmd: "#give spruce_log 32" },
    { name: "Birch Log", cmd: "#give birch_log 32" },
    { name: "Jungle Log", cmd: "#give jungle_log 32" },
    { name: "Dark Oak Log", cmd: "#give dark_oak_log 32" },
    { name: "Acacia Log", cmd: "#give acacia_log 32" },
    { name: "Cherry Log", cmd: "#give cherry_log 32" },
    { name: "Mangrove Log", cmd: "#give mangrove_log 32" },
    { name: "Sand", cmd: "#give sand 64" },
    { name: "Gravel", cmd: "#give gravel 64" },
    { name: "Glass", cmd: "#give glass 64" },
    { name: "Obsidian", cmd: "#give obsidian 16" },
    { name: "Crying Obsidian", cmd: "#give crying_obsidian 8" },
    { name: "Netherrack", cmd: "#give netherrack 64" },
    { name: "End Stone", cmd: "#give end_stone 64" },
    { name: "Torch", cmd: "#give torch 64" },
    { name: "Lantern", cmd: "#give lantern 16" },
    { name: "Campfire", cmd: "#give campfire 4" },
    { name: "Coal", cmd: "#give coal 64" },
    { name: "Charcoal", cmd: "#give charcoal 64" },
    { name: "Iron Ingot", cmd: "#give iron_ingot 32" },
    { name: "Gold Ingot", cmd: "#give gold_ingot 32" },
    { name: "Copper Ingot", cmd: "#give copper_ingot 32" },
    { name: "Diamond", cmd: "#give diamond 16" },
    { name: "Emerald", cmd: "#give emerald 16" },
    { name: "Netherite Ingot", cmd: "#give netherite_ingot 4" },
    { name: "Lapis Lazuli", cmd: "#give lapis_lazuli 64" },
    { name: "Redstone", cmd: "#give redstone 64" },
    { name: "Glowstone Dust", cmd: "#give glowstone_dust 64" },
    { name: "Amethyst Shard", cmd: "#give amethyst_shard 16" },
    { name: "Quartz", cmd: "#give quartz 64" },
    { name: "Stick", cmd: "#give stick 64" },
    { name: "String", cmd: "#give string 64" },
    { name: "Leather", cmd: "#give leather 32" },
    { name: "Feather", cmd: "#give feather 32" },
    { name: "Bone", cmd: "#give bone 32" },
    { name: "Gunpowder", cmd: "#give gunpowder 32" },
    { name: "Ender Pearl", cmd: "#give ender_pearl 8" },
    { name: "Blaze Rod", cmd: "#give blaze_rod 8" },
    { name: "Blaze Powder", cmd: "#give blaze_powder 16" },
    { name: "Ghast Tear", cmd: "#give ghast_tear 4" },
    { name: "Nether Star", cmd: "#give nether_star 1" },
    { name: "Totem of Undying", cmd: "#give totem_of_undying 1" },
    { name: "Elytra", cmd: "#give elytra 1" },
    { name: "Firework Rocket", cmd: "#give firework_rocket 16" },
    { name: "Shield", cmd: "#give shield 1" },
    { name: "Bucket", cmd: "#give bucket 1" },
    { name: "Water Bucket", cmd: "#give water_bucket 1" },
    { name: "Lava Bucket", cmd: "#give lava_bucket 1" },
    { name: "Milk Bucket", cmd: "#give milk_bucket 1" },
    { name: "Bread", cmd: "#give bread 16" },
    { name: "Cooked Beef", cmd: "#give cooked_beef 16" },
    { name: "Cooked Porkchop", cmd: "#give cooked_porkchop 16" },
    { name: "Cooked Chicken", cmd: "#give cooked_chicken 16" },
    { name: "Golden Apple", cmd: "#give golden_apple 4" },
    { name: "Enchanted Golden Apple", cmd: "#give enchanted_golden_apple 1" },
    { name: "Golden Carrot", cmd: "#give golden_carrot 16" },
    { name: "Chorus Fruit", cmd: "#give chorus_fruit 16" },
    { name: "Apple", cmd: "#give apple 16" },
    { name: "Melon Slice", cmd: "#give melon_slice 32" },
    { name: "Sweet Berries", cmd: "#give sweet_berries 32" },
    { name: "Torchflower", cmd: "#give torchflower 4" },
    { name: "Pitcher Plant", cmd: "#give pitcher_plant 4" },
    { name: "Oak Sapling", cmd: "#give oak_sapling 16" },
    { name: "Wheat Seeds", cmd: "#give wheat_seeds 32" },
    { name: "Carrot", cmd: "#give carrot 32" },
    { name: "Potato", cmd: "#give potato 32" },
    { name: "Bone Meal", cmd: "#give bone_meal 64" },
    { name: "Name Tag", cmd: "#give name_tag 1" },
    { name: "Saddle", cmd: "#give saddle 1" },
    { name: "Lead", cmd: "#give lead 4" },
    { name: "Spyglass", cmd: "#give spyglass 1" },
    { name: "Compass", cmd: "#give compass 1" },
    { name: "Clock", cmd: "#give clock 1" },
    { name: "Map", cmd: "#give map 1" },
    { name: "Book", cmd: "#give book 8" },
    { name: "Paper", cmd: "#give paper 32" },
    { name: "Experience Bottle", cmd: "#give experience_bottle 16" },
    { name: "Diamond Pickaxe", cmd: "#give diamond_pickaxe" },
    { name: "Diamond Sword", cmd: "#give diamond_sword" },
    { name: "Diamond Axe", cmd: "#give diamond_axe" },
    { name: "Iron Pickaxe", cmd: "#give iron_pickaxe" },
    { name: "Bow", cmd: "#give bow" },
    { name: "Crossbow", cmd: "#give crossbow" },
    { name: "Trident", cmd: "#give trident" },
    { name: "Netherite Helmet", cmd: "#give netherite_helmet" },
    { name: "Netherite Chestplate", cmd: "#give netherite_chestplate" },
    { name: "Netherite Leggings", cmd: "#give netherite_leggings" },
    { name: "Netherite Boots", cmd: "#give netherite_boots" },
  ],

  equipment: [
    { name: "Diamond Sword · Sharp V", cmd: "#give diamond_sword[sharpness 5, unbreaking 3, mending 1]" },
    { name: "Netherite Sword · Fire", cmd: "#give netherite_sword[sharpness 5, fire aspect 2, looting 3, unbreaking 3]" },
    { name: "Iron Sword · Smite", cmd: "#give iron_sword[smite 5, knockback 2]" },
    { name: "Diamond Axe · Silk", cmd: "#give diamond_axe[efficiency 5, silk touch 1, unbreaking 3]" },
    { name: "Netherite Axe · Sharp", cmd: "#give netherite_axe[sharpness 5, efficiency 5, unbreaking 3]" },
    { name: "Diamond Pick · Fortune", cmd: "#give diamond_pickaxe[efficiency 5, fortune 3, unbreaking 3, mending 1]" },
    { name: "Netherite Pick · Silk", cmd: "#give netherite_pickaxe[efficiency 5, silk touch 1, unbreaking 3]" },
    { name: "Soulbound Pick", cmd: "#give diamond_pickaxe[efficiency 5, soulbound 1, mending 1]" },
    { name: "Diamond Shovel · Silk", cmd: "#give diamond_shovel[efficiency 5, silk touch 1]" },
    { name: "Diamond Hoe", cmd: "#give diamond_hoe[efficiency 5, unbreaking 3]" },
    { name: "Bow · Infinity", cmd: "#give bow[power 5, punch 2, flame 1, infinity 1, unbreaking 3]" },
    { name: "Bow · Mending", cmd: "#give bow[power 5, mending 1, unbreaking 3]" },
    { name: "Crossbow · Multishot", cmd: "#give crossbow[multishot 1, quick charge 3, unbreaking 3]" },
    { name: "Crossbow · Piercing", cmd: "#give crossbow[piercing 4, quick charge 3]" },
    { name: "Trident · Loyalty", cmd: "#give trident[loyalty 3, impaling 5, channeling 1, unbreaking 3]" },
    { name: "Trident · Riptide", cmd: "#give trident[riptide 3, unbreaking 3]" },
    { name: "Netherite Helmet", cmd: "#give netherite_helmet[protection 4, respiration 3, aqua affinity 1, unbreaking 3, mending 1]" },
    { name: "Netherite Chest", cmd: "#give netherite_chestplate[protection 4, unbreaking 3, mending 1]" },
    { name: "Soulbound Chest", cmd: "#give netherite_chestplate[protection 4, soulbound 1, unbreaking 3]" },
    { name: "Netherite Legs", cmd: "#give netherite_leggings[protection 4, swift sneak 3, unbreaking 3, mending 1]" },
    { name: "Netherite Boots", cmd: "#give netherite_boots[protection 4, feather falling 4, depth strider 3, soul speed 3, unbreaking 3, mending 1]" },
    { name: "Diamond Helmet", cmd: "#give diamond_helmet[protection 4, unbreaking 3]" },
    { name: "Diamond Chest · Thorns", cmd: "#give diamond_chestplate[protection 4, thorns 3, unbreaking 3]" },
    { name: "Diamond Legs", cmd: "#give diamond_leggings[protection 4, unbreaking 3]" },
    { name: "Diamond Boots · FF", cmd: "#give diamond_boots[protection 4, feather falling 4, unbreaking 3]" },
    { name: "Elytra · Mending", cmd: "#give elytra[unbreaking 3, mending 1]" },
    { name: "Shield · Unbreaking", cmd: "#give shield[unbreaking 3, mending 1]" },
    { name: "Fishing Rod · Luck", cmd: "#give fishing_rod[luck of the sea 3, lure 3, unbreaking 3, mending 1]" },
  ],

  arrows: [
    { name: "Arrow ×64", cmd: "#give arrow 64" },
    { name: "Spectral Arrow ×16", cmd: "#give spectral_arrow 16" },
    { name: "Poison", cmd: "#give arrow[poison] 16" },
    { name: "Poison II", cmd: "#give arrow[poison 2] 16" },
    { name: "Long Poison", cmd: "#give arrow[long poison] 16" },
    { name: "Harming", cmd: "#give arrow[harming] 16" },
    { name: "Harming II", cmd: "#give tipped_arrow[harming 2] 8" },
    { name: "Slowness", cmd: "#give arrow[slowness] 16" },
    { name: "Slowness II", cmd: "#give arrow[slowness 2] 16" },
    { name: "Weakness", cmd: "#give arrow[weakness] 16" },
    { name: "Long Weakness", cmd: "#give arrow[weakness 2] 16" },
    { name: "Healing", cmd: "#give arrow[healing] 16" },
    { name: "Healing II", cmd: "#give arrow[healing 2] 16" },
    { name: "Regeneration", cmd: "#give arrow[regen] 16" },
    { name: "Regen II", cmd: "#give arrow[regen 2] 16" },
    { name: "Swiftness", cmd: "#give arrow[swiftness] 16" },
    { name: "Swiftness II", cmd: "#give arrow[swiftness 2] 16" },
    { name: "Night Vision", cmd: "#give arrow[night vision] 16" },
    { name: "Invisibility", cmd: "#give arrow[invisibility] 16" },
    { name: "Fire Resistance", cmd: "#give arrow[fire resistance] 16" },
    { name: "Water Breathing", cmd: "#give arrow[water breathing] 16" },
    { name: "Leaping", cmd: "#give arrow[leaping] 16" },
    { name: "Leaping II", cmd: "#give arrow[leaping 2] 16" },
    { name: "Slow Falling", cmd: "#give arrow[slow falling] 16" },
    { name: "Turtle Master", cmd: "#give arrow[turtle master] 16" },
    { name: "Turtle Master II", cmd: "#give arrow[turtle master 2] 16" },
  ],

  books: [
    { name: "Protection IV", cmd: "#give enchanted_book[protection 4]" },
    { name: "Protection + Unbreaking", cmd: "#give enchanted_book[protection 3, unbreaking 3]" },
    { name: "Protection Kit", cmd: "#give enchanted_book[protection 4, unbreaking 3, mending 1]" },
    { name: "Fire Protection IV", cmd: "#give enchanted_book[fire protection 4]" },
    { name: "Blast Protection IV", cmd: "#give enchanted_book[blast protection 4]" },
    { name: "Projectile Protection IV", cmd: "#give enchanted_book[projectile protection 4]" },
    { name: "Feather Falling IV", cmd: "#give enchanted_book[feather falling 4]" },
    { name: "Respiration III", cmd: "#give enchanted_book[respiration 3]" },
    { name: "Aqua Affinity", cmd: "#give enchanted_book[aqua affinity 1]" },
    { name: "Thorns III", cmd: "#give enchanted_book[thorns 3]" },
    { name: "Depth Strider III", cmd: "#give enchanted_book[depth strider 3]" },
    { name: "Frost Walker II", cmd: "#give enchanted_book[frost walker 2]" },
    { name: "Soul Speed III", cmd: "#give enchanted_book[soul speed 3]" },
    { name: "Swift Sneak III", cmd: "#give enchanted_book[swift sneak 3]" },
    { name: "Sharpness V", cmd: "#give enchanted_book[sharpness 5]" },
    { name: "Smite V", cmd: "#give enchanted_book[smite 5]" },
    { name: "Bane of Arthropods V", cmd: "#give enchanted_book[bane of arthropods 5]" },
    { name: "Knockback II", cmd: "#give enchanted_book[knockback 2]" },
    { name: "Fire Aspect II", cmd: "#give enchanted_book[fire aspect 2]" },
    { name: "Looting III", cmd: "#give enchanted_book[looting 3]" },
    { name: "Sweeping Edge III", cmd: "#give enchanted_book[sweeping 3]" },
    { name: "Power V", cmd: "#give enchanted_book[power 5]" },
    { name: "Punch II", cmd: "#give enchanted_book[punch 2]" },
    { name: "Flame", cmd: "#give enchanted_book[flame 1]" },
    { name: "Infinity", cmd: "#give enchanted_book[infinity 1]" },
    { name: "Multishot", cmd: "#give enchanted_book[multishot 1]" },
    { name: "Piercing IV", cmd: "#give enchanted_book[piercing 4]" },
    { name: "Quick Charge III", cmd: "#give enchanted_book[quick charge 3]" },
    { name: "Loyalty III", cmd: "#give enchanted_book[loyalty 3]" },
    { name: "Impaling V", cmd: "#give enchanted_book[impaling 5]" },
    { name: "Riptide III", cmd: "#give enchanted_book[riptide 3]" },
    { name: "Channeling", cmd: "#give enchanted_book[channeling 1]" },
    { name: "Efficiency V", cmd: "#give enchanted_book[efficiency 5]" },
    { name: "Silk Touch", cmd: "#give enchanted_book[silk touch 1]" },
    { name: "Fortune III", cmd: "#give enchanted_book[fortune 3]" },
    { name: "Efficiency + Fortune", cmd: "#give enchanted_book[efficiency 5, fortune 3]" },
    { name: "Luck of the Sea III", cmd: "#give enchanted_book[luck of the sea 3]" },
    { name: "Lure III", cmd: "#give enchanted_book[lure 3]" },
    { name: "Unbreaking III", cmd: "#give enchanted_book[unbreaking 3]" },
    { name: "Mending", cmd: "#give enchanted_book[mending 1]" },
    { name: "Unbreaking + Mending", cmd: "#give enchanted_book[unbreaking 3, mending 1]" },
    { name: "Soulbound", cmd: "#give enchanted_book[soulbound 1]" },
    { name: "Curse of Vanishing", cmd: "#give enchanted_book[vanishing curse 1]" },
    { name: "Curse of Binding", cmd: "#give enchanted_book[binding curse 1]" },
  ],

  potions: [
    { name: "Strength II", cmd: "#give potion[strength 2]" },
    { name: "Swiftness", cmd: "#give potion[swiftness]" },
    { name: "Swiftness II", cmd: "#give potion[swiftness 2]" },
    { name: "Healing II", cmd: "#give potion[healing 2]" },
    { name: "Regen II", cmd: "#give potion[regen 2]" },
    { name: "Fire Resistance", cmd: "#give potion[fire resistance]" },
    { name: "Long Fire Resistance", cmd: "#give potion[long fire resistance]" },
    { name: "Night Vision", cmd: "#give potion[night vision]" },
    { name: "Long Night Vision", cmd: "#give potion[long night vision]" },
    { name: "Invisibility", cmd: "#give potion[invisibility]" },
    { name: "Water Breathing", cmd: "#give potion[water breathing]" },
    { name: "Leaping II", cmd: "#give potion[leaping 2]" },
    { name: "Slow Falling", cmd: "#give potion[slow falling]" },
    { name: "Turtle Master II", cmd: "#give potion[turtle master 2]" },
    { name: "Splash Poison II", cmd: "#give splash_potion[poison 2]" },
    { name: "Splash Weakness II", cmd: "#give splash_potion[weakness 2]" },
    { name: "Splash Harming II", cmd: "#give splash_potion[strong harming]" },
    { name: "Splash Slowness II", cmd: "#give splash_potion[slowness 2]" },
    { name: "Splash Strength II", cmd: "#give splash_potion[strength 2]" },
    { name: "Splash Healing II", cmd: "#give splash_potion[healing 2]" },
    { name: "Lingering Poison", cmd: "#give lingering_potion[long poison]" },
    { name: "Lingering Regen", cmd: "#give lingering_potion[regen]" },
    { name: "Lingering Slowness", cmd: "#give lingering_potion[slowness]" },
    { name: "Water Bottle", cmd: "#give potion[water]" },
    { name: "Awkward", cmd: "#give potion[awkward]" },
    { name: "Mundane", cmd: "#give potion[mundane]" },
    { name: "Thick", cmd: "#give potion[thick]" },
  ],

  curses: [
    {
      name: "Gravel",
      cmd: "#gravel",
      desc: "Drops gravel ahead of the player on a loop for ~67s.",
    },
    {
      name: "Bokuto",
      cmd: "#bokuto",
      desc: "Turns swords into sticks for 67s, then restores them (NBT kept).",
    },
    {
      name: "Stinky",
      cmd: "#stinky",
      desc: "Fills every empty inventory slot with one rotten flesh.",
    },
    {
      name: "Fool's Gold",
      cmd: "#foolsgold",
      desc: "Copper / iron / gold / diamond ores drop dirt for 67s.",
    },
    {
      name: "Jail",
      cmd: "#jail",
      desc: "Glass box (walls + ceiling) for ~15s, then restores blocks.",
    },
    {
      name: "Blink",
      cmd: "#blink",
      desc: "Safe random teleport within about 16 blocks.",
    },
    {
      name: "Disarm",
      cmd: "#disarm",
      desc: "Drops the item in the main hand.",
    },
    {
      name: "Crop Rot",
      cmd: "#croprot",
      desc: "Resets crops / stems / nether wart in the current chunk to stage 0.",
    },
    {
      name: "Yeet",
      cmd: "#yeet",
      desc: "Launches the player. Optional: #yeet N|S|E|W relative to facing.",
    },
    {
      name: "Yeet Forward",
      cmd: "#yeet N",
      desc: "Launch forward (relative to facing).",
    },
    {
      name: "Magnet Off",
      cmd: "#magnetoff",
      desc: "Blocks item pickup for 67s.",
    },
    {
      name: "Shuffle",
      cmd: "#shuffle",
      desc: "Shuffles the hotbar on cast, then every 6s for 67s.",
    },
    {
      name: "Hungry",
      cmd: "#hungry",
      desc: "Applies Hunger for ~67s.",
    },
    {
      name: "Armour Up",
      cmd: "#armourup",
      desc: "Resistance III for ~67s.",
    },
    {
      name: "Sonic",
      cmd: "#sonic",
      desc: "Speed III for ~67s.",
    },
    {
      name: "Midas",
      cmd: "#midas",
      desc: "Kills and ore breaks drop raw gold for 67s.",
    },
    {
      name: "Rust",
      cmd: "#rust",
      desc: "One random damageable item is left with 1 durability.",
    },
    {
      name: "Butterfingers",
      cmd: "#butterfingers",
      desc: "Breaking blocks or hitting mobs drops the held item (67s).",
    },
    {
      name: "Drunk",
      cmd: "#drunk",
      desc: "Inverts movement and look controls for 67s.",
    },
    {
      name: "Feral",
      cmd: "#feral",
      desc: "Nearby neutral / ally mobs attack the player (fish excluded) for 67s.",
    },
    {
      name: "Mend",
      cmd: "#mend",
      desc: "Free repair pulses on held items and equipped armour for 67s.",
    },
    {
      name: "Raid",
      cmd: "#raid",
      desc: "Starts a village raid, or spawns a pillager squad fallback.",
    },
    {
      name: "Static Shock",
      cmd: "#staticshock",
      desc: "Placing blocks: chance of lightning damage for 67s.",
    },
    {
      name: "Cloning",
      cmd: "#cloning",
      desc: "Hitting a mob heals it and spawns full-HP clone(s) for 67s.",
    },
    {
      name: "Nightmare",
      cmd: "#nightmare",
      desc: "Sets midnight and spawns attacking phantoms overhead.",
    },
    {
      name: "Hiccups",
      cmd: "#hiccups",
      desc: "Forces an auto-jump every 1s for 67s.",
    },
    {
      name: "Ender Swap",
      cmd: "#enderswap",
      desc: "Damaging a mob swaps positions with it for 67s.",
    },
    {
      name: "Bad Potato",
      cmd: "#badpotato",
      desc: "Crafted items become poisonous potatoes for 67s.",
    },
    {
      name: "Vampirism",
      cmd: "#vampirism",
      desc: "Sun burns; night grants Strength + Regen for 67s.",
    },
    {
      name: "Infested",
      cmd: "#infested",
      desc: "Breaking stone / natural blocks spawns silverfish for 67s.",
    },
    {
      name: "Webbed",
      cmd: "#webbed",
      desc: "Places a 1×2 cobweb on the player (feet + head), once.",
    },
    {
      name: "Cockbomb",
      cmd: "#cockbomb",
      desc: "Spawns Mr Nugget (creeper-chicken). Fuse after hug/damage; kill for iron.",
    },
    {
      name: "Voidstep",
      cmd: "#voidstep",
      desc: "Teleports to a safe End platform ~67s (timer starts after End loads), then returns.",
    },
  ],
};
